// This file is auto-generated by @hey-api/openapi-ts

export type Comment = {
  readonly id: string;
  readonly created: string;
  readonly modified: string;
  content: string;
  is_removed?: boolean;
  post: string;
  author: number;
};

export type Message = {
  message: string;
};

export type PaginatedCommentList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Comment>;
};

export type PaginatedPostList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Post>;
};

export type PaginatedUserList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<User>;
};

export type PatchedComment = {
  readonly id?: string;
  readonly created?: string;
  readonly modified?: string;
  content?: string;
  is_removed?: boolean;
  post?: string;
  author?: number;
};

export type PatchedPost = {
  readonly id?: string;
  readonly created?: string;
  readonly modified?: string;
  title?: string;
  content?: string;
  is_draft?: boolean;
  author?: number;
};

export type PatchedUser = {
  readonly id?: number;
  email?: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created?: string;
  readonly modified?: string;
  last_login?: string | null;
};

export type Post = {
  readonly id: string;
  readonly created: string;
  readonly modified: string;
  title: string;
  content: string;
  is_draft?: boolean;
  author: number;
};

export type User = {
  readonly id: number;
  email: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created: string;
  readonly modified: string;
  last_login?: string | null;
};

export type ApiCommentsListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ApiCommentsListResponse = PaginatedCommentList;

export type ApiCommentsCreateData = {
  requestBody: Comment;
};

export type ApiCommentsCreateResponse = Comment;

export type ApiCommentsRetrieveData = {
  /**
   * A UUID string identifying this comment.
   */
  id: string;
};

export type ApiCommentsRetrieveResponse = Comment;

export type ApiCommentsUpdateData = {
  /**
   * A UUID string identifying this comment.
   */
  id: string;
  requestBody: Comment;
};

export type ApiCommentsUpdateResponse = Comment;

export type ApiCommentsPartialUpdateData = {
  /**
   * A UUID string identifying this comment.
   */
  id: string;
  requestBody?: PatchedComment;
};

export type ApiCommentsPartialUpdateResponse = Comment;

export type ApiCommentsDestroyData = {
  /**
   * A UUID string identifying this comment.
   */
  id: string;
};

export type ApiCommentsDestroyResponse = void;

export type ApiPostsListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ApiPostsListResponse = PaginatedPostList;

export type ApiPostsCreateData = {
  requestBody: Post;
};

export type ApiPostsCreateResponse = Post;

export type ApiPostsRetrieveData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
};

export type ApiPostsRetrieveResponse = Post;

export type ApiPostsUpdateData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
  requestBody: Post;
};

export type ApiPostsUpdateResponse = Post;

export type ApiPostsPartialUpdateData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
  requestBody?: PatchedPost;
};

export type ApiPostsPartialUpdateResponse = Post;

export type ApiPostsDestroyData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
};

export type ApiPostsDestroyResponse = void;

export type ApiRestRestCheckRetrieveResponse = Message;

export type ApiUsersListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ApiUsersListResponse = PaginatedUserList;

export type ApiUsersCreateData = {
  requestBody: User;
};

export type ApiUsersCreateResponse = User;

export type ApiUsersRetrieveData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type ApiUsersRetrieveResponse = User;

export type ApiUsersUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody: User;
};

export type ApiUsersUpdateResponse = User;

export type ApiUsersPartialUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody?: PatchedUser;
};

export type ApiUsersPartialUpdateResponse = User;

export type ApiUsersDestroyData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type ApiUsersDestroyResponse = void;

export type $OpenApiTs = {
  "/api/comments/": {
    get: {
      req: ApiCommentsListData;
      res: {
        200: PaginatedCommentList;
      };
    };
    post: {
      req: ApiCommentsCreateData;
      res: {
        201: Comment;
      };
    };
  };
  "/api/comments/{id}/": {
    get: {
      req: ApiCommentsRetrieveData;
      res: {
        200: Comment;
      };
    };
    put: {
      req: ApiCommentsUpdateData;
      res: {
        200: Comment;
      };
    };
    patch: {
      req: ApiCommentsPartialUpdateData;
      res: {
        200: Comment;
      };
    };
    delete: {
      req: ApiCommentsDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/posts/": {
    get: {
      req: ApiPostsListData;
      res: {
        200: PaginatedPostList;
      };
    };
    post: {
      req: ApiPostsCreateData;
      res: {
        201: Post;
      };
    };
  };
  "/api/posts/{id}/": {
    get: {
      req: ApiPostsRetrieveData;
      res: {
        200: Post;
      };
    };
    put: {
      req: ApiPostsUpdateData;
      res: {
        200: Post;
      };
    };
    patch: {
      req: ApiPostsPartialUpdateData;
      res: {
        200: Post;
      };
    };
    delete: {
      req: ApiPostsDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/rest/rest-check/": {
    get: {
      res: {
        200: Message;
      };
    };
  };
  "/api/users/": {
    get: {
      req: ApiUsersListData;
      res: {
        200: PaginatedUserList;
      };
    };
    post: {
      req: ApiUsersCreateData;
      res: {
        201: User;
      };
    };
  };
  "/api/users/{id}/": {
    get: {
      req: ApiUsersRetrieveData;
      res: {
        200: User;
      };
    };
    put: {
      req: ApiUsersUpdateData;
      res: {
        200: User;
      };
    };
    patch: {
      req: ApiUsersPartialUpdateData;
      res: {
        200: User;
      };
    };
    delete: {
      req: ApiUsersDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
};
