// This file is auto-generated by @hey-api/openapi-ts

export type AuthToken = {
  username: string;
  password: string;
  readonly token: string;
};

/**
 * Serializer class for Comment model.
 */
export type Comment = {
  readonly id: string;
  readonly author_name: string;
  readonly created: string;
  readonly modified: string;
  content: string;
  is_removed?: boolean;
  post: string;
  author: number;
};

/**
 * Serializer to validate and serialize a message.
 */
export type Message = {
  message: string;
};

export type PaginatedCommentList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Comment>;
};

export type PaginatedPostList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Post>;
};

export type PaginatedUserList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<User>;
};

/**
 * Serializer for the User model.
 */
export type PatchedUser = {
  readonly id?: number;
  name?: string | null;
  slug?: string;
  email?: string;
  readonly created?: string;
  readonly modified?: string;
  last_login?: string | null;
};

/**
 * Serializer for the Post model.
 *
 * This serializer automatically generates fields based on the Post model.
 * It includes all the fields of the model for comprehensive data handling.
 */
export type Post = {
  readonly id: string;
  readonly comments: Array<Comment>;
  readonly author_name: string;
  readonly created: string;
  readonly modified: string;
  title: string;
  content: string;
  is_draft?: boolean;
  author: number;
};

/**
 * Serializer for the User model.
 */
export type User = {
  results?: any;
  readonly id: number;
  name?: string | null;
  slug: string;
  email: string;
  readonly created: string;
  readonly modified: string;
  last_login?: string | null;
};

export type ApiCommentsListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ApiCommentsListResponse = PaginatedCommentList;

export type ApiCommentsCreateData = {
  requestBody: Comment;
};

export type ApiCommentsCreateResponse = Comment;

export type ApiCommentsRetrieveData = {
  /**
   * A UUID string identifying this comment.
   */
  id: string;
};

export type ApiCommentsRetrieveResponse = Comment;

export type ApiCommentsUpdateData = {
  /**
   * A UUID string identifying this comment.
   */
  id: string;
  requestBody: Comment;
};

export type ApiCommentsUpdateResponse = Comment;

export type ApiCommentsDestroyData = {
  /**
   * A UUID string identifying this comment.
   */
  id: string;
};

export type ApiCommentsDestroyResponse = void;

export type ApiObtainAuthTokenCreateData = {
  formData: AuthToken;
};

export type ApiObtainAuthTokenCreateResponse = AuthToken;

export type ApiPostsListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ApiPostsListResponse = PaginatedPostList;

export type ApiPostsCreateData = {
  requestBody: Post;
};

export type ApiPostsCreateResponse = Post;

export type RetrievePostData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
};

export type RetrievePostResponse = Post;

export type ApiPostsUpdateData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
  requestBody: Post;
};

export type ApiPostsUpdateResponse = Post;

export type ApiPostsDestroyData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
};

export type ApiPostsDestroyResponse = void;

export type ApiPostsBySlugListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
  slug: string;
};

export type ApiPostsBySlugListResponse = PaginatedPostList;

export type ApiPostsBySlugCreateData = {
  requestBody: Post;
  slug: string;
};

export type ApiPostsBySlugCreateResponse = Post;

export type RetrievePost2Data = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
  slug: string;
};

export type RetrievePost2Response = Post;

export type ApiPostsBySlugUpdateData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
  requestBody: Post;
  slug: string;
};

export type ApiPostsBySlugUpdateResponse = Post;

export type ApiPostsBySlugDestroyData = {
  /**
   * A UUID string identifying this post.
   */
  id: string;
  slug: string;
};

export type ApiPostsBySlugDestroyResponse = void;

export type ApiRestRestCheckRetrieveResponse = Message;

export type ApiUserBySlugListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
  slug: string;
};

export type ApiUserBySlugListResponse = PaginatedUserList;

export type ApiUserBySlugCreateData = {
  requestBody: User;
  slug: string;
};

export type ApiUserBySlugCreateResponse = User;

export type ApiUserBySlugRetrieveData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  slug: string;
};

export type ApiUserBySlugRetrieveResponse = User;

export type ApiUserBySlugUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody: User;
  slug: string;
};

export type ApiUserBySlugUpdateResponse = User;

export type ApiUserBySlugPartialUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody?: PatchedUser;
  slug: string;
};

export type ApiUserBySlugPartialUpdateResponse = User;

export type ApiUserBySlugDestroyData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  slug: string;
};

export type ApiUserBySlugDestroyResponse = void;

export type ApiUserByTokenListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
  token: string;
};

export type ApiUserByTokenListResponse = PaginatedUserList;

export type ApiUserByTokenCreateData = {
  requestBody: User;
  token: string;
};

export type ApiUserByTokenCreateResponse = User;

export type ApiUserByTokenRetrieveData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  token: string;
};

export type ApiUserByTokenRetrieveResponse = User;

export type ApiUserByTokenUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody: User;
  token: string;
};

export type ApiUserByTokenUpdateResponse = User;

export type ApiUserByTokenPartialUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody?: PatchedUser;
  token: string;
};

export type ApiUserByTokenPartialUpdateResponse = User;

export type ApiUserByTokenDestroyData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  token: string;
};

export type ApiUserByTokenDestroyResponse = void;

export type ApiUsersListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ApiUsersListResponse = PaginatedUserList;

export type ApiUsersCreateData = {
  requestBody: User;
};

export type ApiUsersCreateResponse = User;

export type ApiUsersRetrieveData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type ApiUsersRetrieveResponse = User;

export type ApiUsersUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody: User;
};

export type ApiUsersUpdateResponse = User;

export type ApiUsersPartialUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody?: PatchedUser;
};

export type ApiUsersPartialUpdateResponse = User;

export type ApiUsersDestroyData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type ApiUsersDestroyResponse = void;

export type $OpenApiTs = {
  "/api/comments/": {
    get: {
      req: ApiCommentsListData;
      res: {
        200: PaginatedCommentList;
      };
    };
    post: {
      req: ApiCommentsCreateData;
      res: {
        201: Comment;
      };
    };
  };
  "/api/comments/{id}/": {
    get: {
      req: ApiCommentsRetrieveData;
      res: {
        200: Comment;
      };
    };
    put: {
      req: ApiCommentsUpdateData;
      res: {
        200: Comment;
      };
    };
    delete: {
      req: ApiCommentsDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/obtain-auth-token/": {
    post: {
      req: ApiObtainAuthTokenCreateData;
      res: {
        200: AuthToken;
      };
    };
  };
  "/api/posts/": {
    get: {
      req: ApiPostsListData;
      res: {
        200: PaginatedPostList;
      };
    };
    post: {
      req: ApiPostsCreateData;
      res: {
        201: Post;
      };
    };
  };
  "/api/posts/{id}/": {
    get: {
      req: RetrievePostData;
      res: {
        200: Post;
      };
    };
    put: {
      req: ApiPostsUpdateData;
      res: {
        200: Post;
      };
    };
    delete: {
      req: ApiPostsDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/posts_by_slug/{slug}/": {
    get: {
      req: ApiPostsBySlugListData;
      res: {
        200: PaginatedPostList;
      };
    };
    post: {
      req: ApiPostsBySlugCreateData;
      res: {
        201: Post;
      };
    };
  };
  "/api/posts_by_slug/{slug}/{id}/": {
    get: {
      req: RetrievePost2Data;
      res: {
        200: Post;
      };
    };
    put: {
      req: ApiPostsBySlugUpdateData;
      res: {
        200: Post;
      };
    };
    delete: {
      req: ApiPostsBySlugDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/rest/rest-check/": {
    get: {
      res: {
        200: Message;
      };
    };
  };
  "/api/user_by_slug/{slug}/": {
    get: {
      req: ApiUserBySlugListData;
      res: {
        200: PaginatedUserList;
      };
    };
    post: {
      req: ApiUserBySlugCreateData;
      res: {
        201: User;
      };
    };
  };
  "/api/user_by_slug/{slug}/{id}/": {
    get: {
      req: ApiUserBySlugRetrieveData;
      res: {
        200: User;
      };
    };
    put: {
      req: ApiUserBySlugUpdateData;
      res: {
        200: User;
      };
    };
    patch: {
      req: ApiUserBySlugPartialUpdateData;
      res: {
        200: User;
      };
    };
    delete: {
      req: ApiUserBySlugDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/user_by_token/{token}/": {
    get: {
      req: ApiUserByTokenListData;
      res: {
        200: PaginatedUserList;
      };
    };
    post: {
      req: ApiUserByTokenCreateData;
      res: {
        201: User;
      };
    };
  };
  "/api/user_by_token/{token}/{id}/": {
    get: {
      req: ApiUserByTokenRetrieveData;
      res: {
        200: User;
      };
    };
    put: {
      req: ApiUserByTokenUpdateData;
      res: {
        200: User;
      };
    };
    patch: {
      req: ApiUserByTokenPartialUpdateData;
      res: {
        200: User;
      };
    };
    delete: {
      req: ApiUserByTokenDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/users/": {
    get: {
      req: ApiUsersListData;
      res: {
        200: PaginatedUserList;
      };
    };
    post: {
      req: ApiUsersCreateData;
      res: {
        201: User;
      };
    };
  };
  "/api/users/{id}/": {
    get: {
      req: ApiUsersRetrieveData;
      res: {
        200: User;
      };
    };
    put: {
      req: ApiUsersUpdateData;
      res: {
        200: User;
      };
    };
    patch: {
      req: ApiUsersPartialUpdateData;
      res: {
        200: User;
      };
    };
    delete: {
      req: ApiUsersDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
};
